React/App.js
=> Gm 14 remove altitude change container colour

frontend/reactnative/App.js, frontend/reactnative/lib/Config.js
Implments persistant settings management on mobile devices
=> Merged rp-7-ReactConfigurationManagement and development branches.

database/createscripts/CreateTables.sql
=> updated create scripts to current values

backend/README.md, backend/pom.xml
=> Jf 65 make backend launchable

backend/Dockerfile, backend/README.md
=> Jf 76 build backend to docker image

backend/src/test/asegroup1/api/models/landregistry/LandRegistryDataTest.java, backend/src/test/asegroup1/api/models/landregistry/LandRegistryQueryConstraintTest.java, backend/src/test/asegroup1/api/models/landregistry/LandRegistryQuerySelectTest.java
=> Added seeds for all tests

.travis.yml
Merging updates so @briso7 can use this
=> Added changes to travis file to include java project in build

frontend/reactnative/App.js
Removed comment inside render function
=> Add dummy data markers to map

.travis.yml, backend/README.md
This closes #77 
means that Travis pushes built repositories to https://hub.docker.com/u/asegroup1/ and the server should automatically pull and deploy them
=> Added automatic push to docker repository

frontend/reactnative/App.js
circles appear under the markers
=> added circle for heatmap

backend/pom.xml
Fixes #128 However currently two unit tests are failing in the development branch, therefore, this pr should fail the Travis build
=> Fixed pom.xml so that tests are running from Command Line

.clang-format
Currently only works on Java and I don't know how to get it working with react code and I've done a fair amount on online research. Therefore I've disabled the javascript formatting. 
Note: will need to download new new pre-commit hook for this to work
=> Jf 34 m0 fix pre commit script bug

.travis.yml, backend/sonar-project.properties, frontend/reactnative/app.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gregam3/asegroup1/200)
=> Be 75 m4 automated deployment builds

backend/src/main/java/asegroup1/api/daos/DaoImpl.java, backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java, backend/src/main/java/asegroup1/api/daos/location/LocationDaoImpl.java, backend/src/main/java/asegroup1/api/models/heatmap/Colour.java, backend/src/main/java/asegroup1/api/models/heatmap/HeatMapDataPoint.java, backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryData.java, backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java, frontend/reactnative/App.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gregam3/asegroup1/201)
=> Added Entity wrapper, to ensure it is closed

backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java, frontend/reactnative/App.js, frontend/reactnative/lib/Auth.js, frontend/reactnative/lib/NetworkingLib.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gregam3/asegroup1/210)
=> Rp gm 209 display data loads on move

backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java, frontend/reactnative/lib/NetworkingLib.js
Updated frontend to point to elastic IP
=> Modified update to overrite set records

.clang-format, backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java, backend/src/main/resources/application.properties, backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
This PR is linked to issue #221 
* I've moved the Api Key to the environment variables and created a windows script to set up all the environment variables on google drive https://drive.google.com/file/d/1DnoeYx3GMQZCm0yMNa0BrS3tg-s9M5S1/view?usp=sharing
* Fixed/Suppressed IntelliJ warnings
* Added some TODOs
* Fixed some bugs found by sonar cloud
* Fixed formatting issues
* Fixed Unit tests
* Add the new environment variables first before opening the project in IntelliJ because it didn't pick up the new variable for me. (Not sure what eclipse will do)
* Run the unit tests
* The database update operation method has changed slightly so it would probably be best to test that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Jf 221 clean up land registry service impl

.travis.yml
This PR is linked to issue #220 
Changed the Travis file and removed spaces around the environment variable assignment
Check the Travis build
I don't think its possible to test the changes as it would need to be in master
=> Fix for travis not automatically deploying master branch

frontend/reactnative/App.js
This PR is linked to issue #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gregam3/asegroup1/243)
=> Jh 74m2 street view

backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java, backend/src/main/java/asegroup1/api/models/heatmap/Colour.java, backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java, backend/src/test/java/asegroup1/api/models/heatmap/ColourTest.java, backend/src/test/java/asegroup1/api/models/heatmap/HeatMapDataPointTest.java, backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
This PR is linked to issue #236 
Linked with old PR #242
=> Gm 236m1 test coverage

backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java, backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryData.java, backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryQueryConstraint.java, backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryQuerySelect.java, backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java, backend/src/main/java/asegroup1/api/services/location/LocationServiceImpl.java, backend/src/test/java/asegroup1/api/controllers/LandRegistryControllerTest.java, backend/src/test/java/asegroup1/api/controllers/LocationControllerTest.java, backend/src/test/java/asegroup1/api/controllers/UserControllerTest.java, backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryDataTest.java, backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryQueryConstraintTest.java, backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryQueryGroupTest.java, backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryQuerySelectTest.java, backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryQueryTest.java, backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryQueryTestUtils.java, backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java, backend/src/test/java/asegroup1/api/services/location/LocationServiceImplTest.java, backend/src/test/java/asegroup1/api/services/user/UserServiceImplTest.java
This PR is linked to issue #236
Added many tests including:
Query Generation
Database Update
Controllers
Check the tests run, database updates, app runs fine.
As some implementation has been changed.
Run tests, check over code.
=> Rp 236m0 tests

.travis.yml
=> Travis builds backend first
